name: Build and Publish

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wyze/discord-bot:latest
          secrets: |
            "dotenv=HASURA_API_KEY=${{ secrets.HASURA_API_KEY }}
            HASURA_URL=${{ secrets.HASURA_URL }}
            MARKETPLACE_URL=https://api.thegraph.com/subgraphs/name/vinnytreasure/treasuremarketplace-fast-prod
            SNAPSHOT_URL=${{ secrets.SNAPSHOT_URL }}
            MAGICSWAP_URL=https://api.thegraph.com/subgraphs/name/treasureproject/magicswap-exchange"
